// <auto-generated />
using System;
using BetaPlatform.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BetaPlatform.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261007093245_AddWorkOrderInputProduct")]
    partial class AddWorkOrderInputProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BetaPlatform.Data.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("BetaPlatform.Data.Entities.ErpSetting", b =>
                {
                    b.Property<int>("ErpSettingId")
                        .HasColumnType("int")
                        .HasColumnName("erp_setting_id");

                    b.Property<string>("ApiToken")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("api_token");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("updated_by");

                    b.HasKey("ErpSettingId");

                    b.ToTable("erp_settings");
                });

            modelBuilder.Entity("BetaPlatform.Data.Entities.Machine", b =>
                {
                    b.Property<int>("MachineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("machine_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MachineId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_running");

                    b.Property<string>("MachineCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("machine_code");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("machine_name");

                    b.Property<int>("MachineTypeId")
                        .HasColumnType("int")
                        .HasColumnName("machine_type_id");

                    b.HasKey("MachineId");

                    b.HasIndex("MachineCode")
                        .IsUnique();

                    b.HasIndex("MachineName")
                        .IsUnique();

                    b.HasIndex("MachineTypeId");

                    b.ToTable("machines");
                });

            modelBuilder.Entity("BetaPlatform.Data.Entities.MachineKpi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("code");

                    b.Property<int>("DataType")
                        .HasColumnType("int")
                        .HasColumnName("data_type");

                    b.Property<bool>("EnableLog")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("enable_log");

                    b.Property<string>("LocationAddress")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("location_address");

                    b.Property<int>("LogPerMs")
                        .HasColumnType("int")
                        .HasColumnName("log_per_ms");

                    b.Property<string>("LogTableName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("log_table_name");

                    b.Property<int>("Module")
                        .HasColumnType("int")
                        .HasColumnName("module");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<int>("Source")
                        .HasColumnType("int")
                        .HasColumnName("source");

                    b.Property<string>("SourceIdentifier")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("source_identifier");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("unit");

                    b.Property<decimal?>("Value")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("SourceIdentifier");

                    b.ToTable("machines_kpis");
                });

            modelBuilder.Entity("BetaPlatform.Data.Entities.MachineMasterData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("code");

                    b.Property<int>("DataType")
                        .HasColumnType("int")
                        .HasColumnName("data_type");

                    b.Property<bool>("EnableLog")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("enable_log");

                    b.Property<string>("LocationAddress")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("location_address");

                    b.Property<int>("LogPerMs")
                        .HasColumnType("int")
                        .HasColumnName("log_per_ms");

                    b.Property<string>("LogTableName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("log_table_name");

                    b.Property<int>("Module")
                        .HasColumnType("int")
                        .HasColumnName("module");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<int>("Source")
                        .HasColumnType("int")
                        .HasColumnName("source");

                    b.Property<string>("SourceIdentifier")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("source_identifier");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("unit");

                    b.Property<decimal?>("Value")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("SourceIdentifier");

                    b.ToTable("machines_master_data");
                });

            modelBuilder.Entity("BetaPlatform.Data.Entities.MachineProperty", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code");

                    b.Property<int?>("DataType")
                        .HasColumnType("int")
                        .HasColumnName("data_type");

                    b.Property<bool?>("EnableLog")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("enable_log");

                    b.Property<string>("LocationAddress")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("location_address");

                    b.Property<uint?>("LogPerMs")
                        .HasColumnType("int unsigned")
                        .HasColumnName("log_per_ms");

                    b.Property<string>("LogTableName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("log_table_name");

                    b.Property<int>("MachineId")
                        .HasColumnType("int")
                        .HasColumnName("machine_id");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("machine_name");

                    b.Property<int?>("Module")
                        .HasColumnType("int")
                        .HasColumnName("module");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int?>("Source")
                        .HasColumnType("int")
                        .HasColumnName("source");

                    b.Property<string>("SourceIdentifier")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("source_identifier");

                    b.Property<int?>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("unit");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.HasIndex("Name");

                    b.HasIndex("SourceIdentifier");

                    b.HasIndex("MachineId", "Name", "Code")
                        .IsUnique()
                        .HasDatabaseName("uk_machine_prop_detailed");

                    b.ToTable("machine_properties");
                });

            modelBuilder.Entity("BetaPlatform.Data.Entities.MachineTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("code");

                    b.Property<int>("DataType")
                        .HasColumnType("int")
                        .HasColumnName("data_type");

                    b.Property<bool>("EnableLog")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("enable_log");

                    b.Property<string>("LocationAddress")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("location_address");

                    b.Property<int>("LogPerMs")
                        .HasColumnType("int")
                        .HasColumnName("log_per_ms");

                    b.Property<string>("LogTableName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("log_table_name");

                    b.Property<int>("MachineId")
                        .HasColumnType("int")
                        .HasColumnName("machine_id");

                    b.Property<string>("MachineName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("machine_name");

                    b.Property<int>("Module")
                        .HasColumnType("int")
                        .HasColumnName("module");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<int>("Source")
                        .HasColumnType("int")
                        .HasColumnName("source");

                    b.Property<string>("SourceIdentifier")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("source_identifier");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("unit");

                    b.Property<decimal?>("Value")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.HasIndex("Source");

                    b.HasIndex("SourceIdentifier");

                    b.ToTable("machine_tags");
                });

            modelBuilder.Entity("BetaPlatform.Data.Entities.MachineType", b =>
                {
                    b.Property<int>("MachineTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("machine_type_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MachineTypeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("name");

                    b.Property<string>("NameEnglish")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("name_english");

                    b.Property<string>("ProductionLine")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("production_line");

                    b.HasKey("MachineTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("machine_types");

                    b.HasData(
                        new
                        {
                            MachineTypeId = 1,
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Forming Machine",
                            NameEnglish = "Forming Machine",
                            ProductionLine = "Armor Rod & Guy Grip line"
                        },
                        new
                        {
                            MachineTypeId = 2,
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Flat Washer Line",
                            NameEnglish = "Flat Washer Line",
                            ProductionLine = "Flat Washer Line"
                        });
                });

            modelBuilder.Entity("BetaPlatform.Data.Entities.OeeData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Availability")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("availability");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("MachineId")
                        .HasColumnType("int")
                        .HasColumnName("machine_id");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<decimal>("Performance")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("performance");

                    b.Property<decimal>("Quality")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("quality");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("status");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("timestamp");

                    b.Property<decimal>("TotalCount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("total_count");

                    b.Property<decimal>("TotalGoods")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("total_goods");

                    b.Property<decimal>("TotalWeight")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("total_weight");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("MachineId", "Timestamp");

                    b.ToTable("oee_data");
                });

            modelBuilder.Entity("BetaPlatform.Data.Entities.PowerData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("A1")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("a1");

                    b.Property<decimal?>("A2")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("a2");

                    b.Property<decimal?>("A3")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("a3");

                    b.Property<decimal?>("AAvg")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("a_avg");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("Frequency")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("frequency");

                    b.Property<decimal?>("KwHr")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("kw_hr");

                    b.Property<int>("MachineId")
                        .HasColumnType("int")
                        .HasColumnName("machine_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("timestamp");

                    b.Property<decimal?>("V1")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("v1");

                    b.Property<decimal?>("V12")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("v12");

                    b.Property<decimal?>("V13")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("v13");

                    b.Property<decimal?>("V2")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("v2");

                    b.Property<decimal?>("V23")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("v23");

                    b.Property<decimal?>("V3")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("v3");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("MachineId", "Timestamp");

                    b.ToTable("power_data");
                });

            modelBuilder.Entity("BetaPlatform.Data.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("product_code");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("product_name");

                    b.Property<string>("ProductNameEnglish")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("product_name_english");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("unit");

                    b.HasKey("ProductId");

                    b.HasIndex("Category");

                    b.HasIndex("IsActive");

                    b.HasIndex("ProductCode")
                        .IsUnique();

                    b.ToTable("products");
                });

            modelBuilder.Entity("BetaPlatform.Data.Entities.SourceAvailable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Enable")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("enable");

                    b.Property<int>("Module")
                        .HasColumnType("int")
                        .HasColumnName("module");

                    b.Property<int>("Source")
                        .HasColumnType("int")
                        .HasColumnName("source");

                    b.Property<string>("SourceConfiguration")
                        .HasColumnType("text")
                        .HasColumnName("source_configuration");

                    b.Property<string>("SourceIdentifier")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("source_identifier");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Source");

                    b.HasIndex("SourceIdentifier")
                        .IsUnique();

                    b.ToTable("sources_available");
                });

            modelBuilder.Entity("BetaPlatform.Data.Entities.WorkOrder", b =>
                {
                    b.Property<int>("WorkOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("work_order_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("WorkOrderId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("finished_at");

                    b.Property<DateTime?>("FirstStartedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("first_started_at");

                    b.Property<decimal?>("HourRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("hour_rate");

                    b.Property<int>("InputProductId")
                        .HasColumnType("int")
                        .HasColumnName("input_product_id");

                    b.Property<int?>("LineSetupTimeMinutes")
                        .HasColumnType("int")
                        .HasColumnName("line_setup_time_minutes");

                    b.Property<int?>("MachineId")
                        .HasColumnType("int")
                        .HasColumnName("machine_id");

                    b.Property<int?>("MachineTypeId")
                        .HasColumnType("int")
                        .HasColumnName("machine_type");

                    b.Property<int?>("OrderTypeId")
                        .HasColumnType("int")
                        .HasColumnName("order_type");

                    b.Property<int>("OutputProductId")
                        .HasColumnType("int")
                        .HasColumnName("output_product_id");

                    b.Property<DateTime>("PlannedStartTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("planned_start_time");

                    b.Property<decimal>("QtyToManufacture")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("qty_to_manufacture");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int>("SyncStatus")
                        .HasColumnType("int")
                        .HasColumnName("sync_status");

                    b.Property<int?>("TotalMixedData")
                        .HasColumnType("int")
                        .HasColumnName("total_mixed_data");

                    b.Property<decimal>("TotalRuntime")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_runtime");

                    b.Property<string>("WorkOrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("work_order_number");

                    b.Property<decimal?>("WorkstationCapabilityPerHour")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("workstation_capability_per_hour");

                    b.HasKey("WorkOrderId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("InputProductId");

                    b.HasIndex("MachineId");

                    b.HasIndex("MachineTypeId");

                    b.HasIndex("OrderTypeId");

                    b.HasIndex("OutputProductId");

                    b.HasIndex("Status");

                    b.HasIndex("WorkOrderNumber")
                        .IsUnique();

                    b.ToTable("work_orders");
                });

            modelBuilder.Entity("BetaPlatform.Data.Entities.WorkOrderInput", b =>
                {
                    b.Property<int>("InputId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("input_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("InputId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int?>("SourceOutputId")
                        .HasColumnType("int")
                        .HasColumnName("source_output_id");

                    b.Property<decimal>("Weight")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("weight");

                    b.Property<int>("WorkOrderId")
                        .HasColumnType("int")
                        .HasColumnName("work_order_id");

                    b.HasKey("InputId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SourceOutputId")
                        .IsUnique();

                    b.HasIndex("WorkOrderId");

                    b.ToTable("work_order_inputs");
                });

            modelBuilder.Entity("BetaPlatform.Data.Entities.WorkOrderInputProduct", b =>
                {
                    b.Property<int>("WorkOrderInputProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("work_order_input_product_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("WorkOrderInputProductId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("Position")
                        .HasColumnType("int")
                        .HasColumnName("position");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("WorkOrderId")
                        .HasColumnType("int")
                        .HasColumnName("work_order_id");

                    b.HasKey("WorkOrderInputProductId");

                    b.HasIndex("ProductId");

                    b.HasIndex("WorkOrderId", "Position");

                    b.HasIndex("WorkOrderId", "ProductId")
                        .IsUnique();

                    b.ToTable("work_order_input_products");
                });

            modelBuilder.Entity("BetaPlatform.Data.Entities.WorkOrderOutput", b =>
                {
                    b.Property<int>("OutputId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("output_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OutputId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("notes");

                    b.Property<bool>("PrintStatus")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("print_status");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int")
                        .HasColumnName("sequence_number");

                    b.Property<string>("UniqueCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("unique_code");

                    b.Property<decimal>("Weight")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("weight");

                    b.Property<int>("WorkOrderId")
                        .HasColumnType("int")
                        .HasColumnName("work_order_id");

                    b.HasKey("OutputId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PrintStatus");

                    b.HasIndex("UniqueCode")
                        .IsUnique();

                    b.HasIndex("WorkOrderId");

                    b.ToTable("work_order_outputs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BetaPlatform.Data.Entities.Machine", b =>
                {
                    b.HasOne("BetaPlatform.Data.Entities.MachineType", "MachineType")
                        .WithMany("Machines")
                        .HasForeignKey("MachineTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MachineType");
                });

            modelBuilder.Entity("BetaPlatform.Data.Entities.MachineProperty", b =>
                {
                    b.HasOne("BetaPlatform.Data.Entities.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BetaPlatform.Data.Entities.SourceAvailable", "SourceAvailable")
                        .WithMany()
                        .HasForeignKey("SourceIdentifier")
                        .HasPrincipalKey("SourceIdentifier")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Machine");

                    b.Navigation("SourceAvailable");
                });

            modelBuilder.Entity("BetaPlatform.Data.Entities.MachineTag", b =>
                {
                    b.HasOne("BetaPlatform.Data.Entities.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("BetaPlatform.Data.Entities.OeeData", b =>
                {
                    b.HasOne("BetaPlatform.Data.Entities.Machine", "Machine")
                        .WithMany("OeeData")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BetaPlatform.Data.Entities.WorkOrder", "WorkOrder")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Machine");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("BetaPlatform.Data.Entities.PowerData", b =>
                {
                    b.HasOne("BetaPlatform.Data.Entities.Machine", "Machine")
                        .WithMany("PowerData")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("BetaPlatform.Data.Entities.WorkOrder", b =>
                {
                    b.HasOne("BetaPlatform.Data.Entities.Product", "InputProduct")
                        .WithMany()
                        .HasForeignKey("InputProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BetaPlatform.Data.Entities.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BetaPlatform.Data.Entities.MachineType", "MachineType")
                        .WithMany()
                        .HasForeignKey("MachineTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BetaPlatform.Data.Entities.MachineType", "OrderType")
                        .WithMany()
                        .HasForeignKey("OrderTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BetaPlatform.Data.Entities.Product", "OutputProduct")
                        .WithMany()
                        .HasForeignKey("OutputProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InputProduct");

                    b.Navigation("Machine");

                    b.Navigation("MachineType");

                    b.Navigation("OrderType");

                    b.Navigation("OutputProduct");
                });

            modelBuilder.Entity("BetaPlatform.Data.Entities.WorkOrderInput", b =>
                {
                    b.HasOne("BetaPlatform.Data.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BetaPlatform.Data.Entities.WorkOrderOutput", "SourceOutput")
                        .WithOne("ConsumedBy")
                        .HasForeignKey("BetaPlatform.Data.Entities.WorkOrderInput", "SourceOutputId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BetaPlatform.Data.Entities.WorkOrder", "WorkOrder")
                        .WithMany("Inputs")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("SourceOutput");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("BetaPlatform.Data.Entities.WorkOrderInputProduct", b =>
                {
                    b.HasOne("BetaPlatform.Data.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BetaPlatform.Data.Entities.WorkOrder", "WorkOrder")
                        .WithMany("InputProducts")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("BetaPlatform.Data.Entities.WorkOrderOutput", b =>
                {
                    b.HasOne("BetaPlatform.Data.Entities.WorkOrder", "WorkOrder")
                        .WithMany("Outputs")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BetaPlatform.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BetaPlatform.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BetaPlatform.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BetaPlatform.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BetaPlatform.Data.Entities.Machine", b =>
                {
                    b.Navigation("OeeData");

                    b.Navigation("PowerData");
                });

            modelBuilder.Entity("BetaPlatform.Data.Entities.MachineType", b =>
                {
                    b.Navigation("Machines");
                });

            modelBuilder.Entity("BetaPlatform.Data.Entities.WorkOrder", b =>
                {
                    b.Navigation("InputProducts");

                    b.Navigation("Inputs");

                    b.Navigation("Outputs");
                });

            modelBuilder.Entity("BetaPlatform.Data.Entities.WorkOrderOutput", b =>
                {
                    b.Navigation("ConsumedBy");
                });
#pragma warning restore 612, 618
        }
    }
}
